spring:
    application:
        name: customer-management-service
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console.enabled: true

    jpa:
        hibernate:
            ddl-auto: update  # "create" will recreate the schema every restart, while "update" will modify it without dropping tables
        show-sql: true       # Optional: shows SQL queries in the console
server:
    port: 8070